import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:omama/menus/models_card/local.dart';

const readme =
    "![](/assets/library/deepseek-v3/069ccc94-63b0-41e6-b2b3-e8e56068ab1a)\n\nDeepSeek’s first-generation reasoning models, achieving performance comparable to OpenAI-o1 across math, code, and reasoning tasks.\n\n## Models\n\n**DeepSeek-R1**\n\n```\nollama run deepseek-r1:671b\n```\n\n### Distilled models\n\nDeepSeek team has demonstrated that the reasoning patterns of larger models can be distilled into smaller models, resulting in better performance compared to the reasoning patterns discovered through RL on small models.\n\nBelow are the models created via fine-tuning against several dense models widely used in the research community using reasoning data generated by DeepSeek-R1. The evaluation results demonstrate that the distilled smaller dense models perform exceptionally well on benchmarks.\n\n**DeepSeek-R1-Distill-Qwen-1.5B**\n\n```\nollama run deepseek-r1:1.5b\n```\n\n**DeepSeek-R1-Distill-Qwen-7B**\n\n```\nollama run deepseek-r1:7b\n```\n\n**DeepSeek-R1-Distill-Llama-8B**\n\n```\nollama run deepseek-r1:8b\n```\n\n**DeepSeek-R1-Distill-Qwen-14B**\n\n```\nollama run deepseek-r1:14b\n```\n\n**DeepSeek-R1-Distill-Qwen-32B**\n\n```\nollama run deepseek-r1:32b\n```\n\n**DeepSeek-R1-Distill-Llama-70B**\n\n```\nollama run deepseek-r1:70b\n```\n\n![deepseek](/assets/library/deepseek-r1/e44d096e-fa46-4cae-b2f2-53991e8c8da0)\n\n### License\n\nThe model weights are licensed under the MIT License. DeepSeek-R1 series support commercial use, allow for any modifications and derivative works, including, but not limited to, distillation for training other LLMs. Please note that:\n\nThe Qwen distilled models are derived from Qwen-2.5 series, which are originally licensed under Apache 2.0 License, and now finetuned with 800k samples curated with DeepSeek-R1.\n\nThe Llama 8B distilled model is derived from Llama3.1-8B-Base and is originally licensed under llama3.1 license.\n\nThe Llama 70B distilled model is derived from Llama3.3-70B-Instruct and is originally licensed under llama3.3 license.";

class LocalModels extends ConsumerStatefulWidget {
  const LocalModels({super.key});

  @override
  ConsumerState<LocalModels> createState() => _LocalModels();
}

class _LocalModels extends ConsumerState<LocalModels> {
  var textController = TextEditingController();
  var scrollController = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Text("Downloaded Models", style: TextStyle(color: Colors.white)),
        SizedBox(height: 30),
        TextField(
          style: TextStyle(color: Colors.white),
          textAlign: TextAlign.center,
          controller: textController,
          decoration: InputDecoration(
            hintText: "search",
            hintStyle: TextStyle(color: Colors.white.withAlpha(150)),
          ),
        ),
        SizedBox(height: 30),
        Expanded(
          child: ListView.builder(
            controller: scrollController,
            itemCount: 10,
            itemBuilder: (BuildContext context, count) {
              return LocalModelCard(
                name: "deepSeek",
                summary: "best model ever",
                category: "Other",
                readme: readme,
                varients: [("7b", "5GB")],
              );
            },
          ),
        ),
      ],
    );
  }
}
